[package]
name = "net"
version = "0.1.0"
authors = ["loovjo <jonathan.loov@gmail.com>"]

[dependencies]
rocket = "0.3.2"
rocket_codegen = "0.3.2"

zip = "0.2.6"
reqwest = "0.7.3"
chrono = "0.4"
select = "0.4.2"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"